### PR TITLE
del(24.11 /public /src): MAJOR CHANGE : READ CAREFULLY

### PR DESCRIPTION
**Pull request by elmaruz**
Deleted shoes.json from /public, replaced with allShoes.json and changed fetch argument in App.js in order to reflect data source change. Shouldn't break anything related to other components.

This was done in order to be able to retrieve shoes size data (shoes.json incomplete).

### CODE REVIEW

**Comment by AlanMauricioCastillo** [comment]
cuidado en la parte superior del App faltan importaciones!!!!!!!!!

**Comment by elmaruz** [comment]
Cuales imports? Sent from Mail for Windows From: Mauricio Alan CastilloSent: 24 November 2021 13:03To: sergiogrimaldo/EcommercePGCc: elmaruz; AuthorSubject: Re: [sergiogrimaldo/EcommercePG] del(24.11 /public /src): MAJOR CHANGE : READ CAREFULLY (PR #34) cuidado en la parte superior del App faltan importaciones!!!!!!!!!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by AlanMauricioCastillo** [comment]
importante copiar y pegar el json de allShoes en la carpeta client/public de lo contrario no funciona el fetch

**Comment by elmaruz** [comment]
Es lo que hice, mira los commits.

**Review by sergiogrimaldo — APPROVED** [review]

**Pull request merged**
